"""Flowerie 消息边界抽象（Phase 3：只定义契约，不实现 OneBot 细节）。

- InternalEvent：主流程业务事件（领域语义；禁止包含 post_type/sub_type/message_type）
- EventParser：OneBot raw dict → InternalEvent（机械转换的唯一位置）
- MessageSender：发送/查询出口契约（与现有 Sender 签名逐一一致——鸭子类型，
  Sender 隐式满足，无需实现类）

约束：
- Python 3.9 兼容（typing 旧式写法）
- 冻结业务层（人格/记忆/AI/MCP/知识库）不得 import 本模块读取 raw_data
"""
from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional, Protocol, Tuple


@dataclass
class InternalEvent:
    """领域事件（按 Flowerie 真实消费方设计，不复制 OneBot Event）。"""

    event_id: str = ""                 # 稳定标识：kind:scope:group:actor:message_id:time
    kind: str = "unknown"              # message | notice | request | lifecycle
    scope: str = ""                    # group | private | ""（会话范围）
    group_id: Optional[int] = None
    actor_id: Optional[int] = None     # 触发者 QQ
    message_id: Optional[int] = None
    timestamp: Optional[int] = None    # 平台事件时间（秒）
    # 内容（解析后结构化；等价于 file_parser.extract_mention_and_text / 段扫描）
    text: str = ""                     # 纯文本（at/text 段拼合后 strip）
    mentions: List[str] = field(default_factory=list)   # @ 的 QQ 列表（含 all）
    images: List[str] = field(default_factory=list)     # 图片 url 列表（url 优先，file 兜底——兼容视图）
    image_files: List[str] = field(default_factory=list)  # 图片本地 file 路径（OneBot 标准字段，识别优先）
    reply_id: Optional[int] = None     # 引用消息 id
    notice_kind: str = ""              # poke / group_increase / group_upload / ...
    request_kind: str = ""             # friend / group（申请类事件）
    lifecycle_kind: str = ""           # enable / disable / connect（生命周期事件）
    operator_id: Optional[int] = None  # 操作者（群管变动等）；缺省=actor_id
    target_id: Optional[int] = None    # 目标（poke 的被戳者等在边界提取）
    notice_file: Dict[str, Any] = field(default_factory=dict)  # 上传/通知文件对象（边界提取）
    # 派生语义（router/策略层直接使用）
    is_mentioned: bool = False         # @bot_qq 或 @all
    is_reply_to_bot: bool = False
    has_reply_to_other: bool = False
    has_at_others: bool = False
    # 高级段摘要（合并转发/卡片等）：(kind, data)；data 为平台释义 dict（解析期使用）
    segments_summary: List[Tuple[str, dict]] = field(default_factory=list)
    # 原始消息段（浅拷贝的段数组，供 GroupMessage.message_array 兼容组装；
    # 业务如需按段处理请用 segments_summary/语义字段——不要把 OneBot JSON 读进业务）
    message_segments: List[dict] = field(default_factory=list)
    # 隔离保留：仅供 EventParser 内部/调试；业务层禁止读取（审查红线）
    raw_data: Dict[str, Any] = field(default_factory=dict, repr=False)


class EventParser(Protocol):
    """OneBot raw dict → InternalEvent（转换结果须与 message_router 现有行为等价）。"""

    def parse(self, raw: Dict[str, Any]) -> InternalEvent:
        ...


class MessageSender(Protocol):
    """发送/查询出口契约。

    签名、返回值与异常行为与 src/services/sender.Sender 保持完全一致
    （本 Protocol 仅为类型契约；Sender 无需任何修改即满足）。
    """

    async def send_group_message(self, group_id: int, message: str, retries: int = 2) -> bool: ...
    async def send_group_message_with_image(self, group_id: int, text: str, image_path: str,
                                            retries: int = 2) -> bool: ...
    async def send_private_message(self, user_id: int, message: str) -> bool: ...
    async def send_msg_raw(self, target: str, target_id: int, message,
                           reply_id=None, retries: int = 2) -> dict: ...
    async def delete_msg(self, message_id: int) -> bool: ...
    async def get_msg(self, message_id: int) -> dict: ...
    async def get_group_msg_history(self, group_id: int, count: int = 15) -> dict: ...
    async def get_group_member_info(self, group_id: int, user_id: int) -> dict: ...
    async def get_group_member_list(self, group_id: int) -> dict: ...
    async def set_group_ban(self, group_id: int, user_id: int, duration_seconds: int) -> bool: ...
    async def set_group_kick(self, group_id: int, user_id: int, reject_add: bool = False) -> bool: ...
    async def set_group_admin(self, group_id: int, user_id: int, enable: bool) -> bool: ...
    async def set_group_whole_ban(self, group_id: int, enable: bool) -> dict: ...
    async def set_group_name(self, group_id: int, name: str) -> dict: ...
    async def set_group_card(self, group_id: int, user_id: int, card: str) -> dict: ...
    async def set_group_special_title(self, group_id: int, user_id: int, title: str) -> dict: ...
    async def send_group_notice(self, group_id: int, content: str, image: str = "") -> dict: ...
    async def get_group_notice(self, group_id: int) -> dict: ...
    async def get_group_root_files(self, group_id: int) -> dict: ...
    async def get_group_files_by_folder(self, group_id: int, folder_id: str) -> dict: ...
    async def get_group_file_url(self, group_id: int, file_id: str, busid: int) -> dict: ...
    async def set_essence_msg(self, message_id: int) -> dict: ...
    async def delete_essence_msg(self, message_id: int) -> dict: ...
    async def set_friend_profile_like(self, user_id: int) -> dict: ...
    async def get_friend_list(self) -> dict: ...
    async def get_login_info(self) -> dict: ...
    async def get_online_clients(self) -> dict: ...
    async def set_qq_profile(self, nickname: str = "", signature: str = "") -> dict: ...
    async def get_group_config(self, group_id: int) -> dict: ...
    async def set_group_config(self, group_id: int, **kwargs) -> dict: ...
    async def get_group_res(self, group_id: int, res_type: str) -> dict: ...
    async def send_poke(self, group_id: int, user_id: int) -> dict: ...
    async def set_react(self, message_id: int, react_type: int) -> dict: ...
    async def set_friend_add_request(self, flag: str, approve: bool, remark: str = "") -> bool: ...
    async def set_group_add_request(self, flag: str, approve: bool, reason: str = "") -> bool: ...
